name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}
          
      - name: Define private key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Pull latest code and run deploy.sh on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ec2-user@3.15.13.239 << 'EOF'
            cd /home/ec2-user/personal-website
            git pull origin main
            bash /home/ec2-user/personal-website/scripts/deploy.sh
          EOF
